cmake_minimum_required(VERSION 3.28)
project(Skylabs HOMEPAGE_URL "https://grinlexstudios.ru" VERSION 0.0.0 LANGUAGES CXX C)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_COLOR_DIAGNOSTICS ON)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
list(APPEND CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake/Modules")

# Options
if(ANDROID)
    set(enable_steam_default OFF)
else()
    set(enable_steam_default ON)
endif()

option(SKYLABS_ENABLE_STEAM "Enable Steamworks SDK" ${enable_steam_default})

# Global settings
include(Skylabs/Skylabs)
include(Skylabs/CompileOptions)
include(Skylabs/ThirdParty)

# Skylabs variables
set(SKYLABS_ROOT_DIR ${PROJECT_SOURCE_DIR})
set(SKYLABS_ASSETS_DIR ${SKYLABS_ROOT_DIR}/assets)
set(SKYLABS_ANDROID_DIR ${SKYLABS_ROOT_DIR}/android)
set(SKYLABS_ANDROID_GENERATED_ASSETS_DIR ${SKYLABS_ROOT_DIR}/android/app/src/main/assets)

set(SKYLABS_ROOT_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/.output/$<CONFIG>)
set(SKYLABS_BIN_OUTPUT_DIRECTORY ${SKYLABS_ROOT_OUTPUT_DIRECTORY}/bin)
set(SKYLABS_LIB_OUTPUT_DIRECTORY ${SKYLABS_ROOT_OUTPUT_DIRECTORY}/lib)
set(SKYLABS_SHADER_OUTPUT_DIRECTORY ${SKYLABS_ROOT_OUTPUT_DIRECTORY}/shaders)

set(SKYLABS_NAME ${PROJECT_NAME})
set(SKYLABS_GAME_NAME ${PROJECT_NAME})
set(SKYLABS_COMPANY "Grinlex Stydios")
set(SKYLABS_COPYRIGHT "MIT License. Copyright (c) 2025-present ${SKYLABS_COMPANY}")
set(SKYLABS_HOMEPAGE ${CMAKE_PROJECT_HOMEPAGE_URL})
set(SKYLABS_VERSION ${PROJECT_VERSION})
set(SKYLABS_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(SKYLABS_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(SKYLABS_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(SKYLABS_VERSION_WORD "Melons")

# Skylabs
include_directories("${PROJECT_SOURCE_DIR}")
add_subdirectory(skylabs)
